/* test.java */
/* Generated By:JavaCC: Do not edit this line. test.java */
package homework;
import java.util.Scanner;
import java.util.*;
public class test implements testConstants {
public static void main(String[] args) throws ParseException
        {
                System.out.print("Hello World \n");
                test parser = new test(System.in);
                Scanner input = new Scanner(System.in);
                parser.start();
//		int c=1;		
//		while(c!=0) {
//		    System.out.println("----------------------------------");
//			
//			System.out.println("accept");
//			System.out.println("To Stop Enter 0 To Countinue Enter Another Number");
//			c=input.nextInt();		
//		}
        System.out.println("FINISH");

        }

  static final public void start() throws ParseException {
    select();
}

//Contains a number or string
  static final public void terms() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case number:{
      jj_consume_token(number);
      break;
      }
    case STRING:{
      jj_consume_token(STRING);
      break;
      }
    default:
      jj_la1[0] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

//Contains a number or string or calculation or boolean
  static final public void values() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case pan:{
      jj_consume_token(pan);
      jj_consume_token(STRING);
      jj_consume_token(pan);
      break;
      }
    case number:
    case STRING:{
      terms();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:
      case subtract:
      case multiply:
      case division:
      case rest:{
        label_1:
        while (true) {
          operator();
          terms();
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case PLUS:
          case subtract:
          case multiply:
          case division:
          case rest:{
            ;
            break;
            }
          default:
            jj_la1[1] = jj_gen;
            break label_1;
          }
        }
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        ;
      }
      break;
      }
    case BOOLEAN:{
      jj_consume_token(BOOLEAN);
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void type() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case DOUBLE:{
      jj_consume_token(DOUBLE);
      break;
      }
    case CHR:{
      jj_consume_token(CHR);
      break;
      }
    case STR:{
      jj_consume_token(STR);
      break;
      }
    case BOL:{
      jj_consume_token(BOL);
      break;
      }
    case FLOAT:{
      jj_consume_token(FLOAT);
      break;
      }
    case INIT:{
      jj_consume_token(INIT);
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

//Definition of variables
  static final public void declear() throws ParseException {
    type();
    jj_consume_token(STRING);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case equal:{
      jj_consume_token(equal);
      values();
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      ;
    }
}

//Assign of variables
  static final public void assign() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case number:{
      jj_consume_token(number);
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      ;
    }
    jj_consume_token(equal);
    values();
}

//Select a mathematical or logical operation or assign
//void select(): { } {
//terms()(oparith()|assign()|oplogic())
//}
  static final public void select() throws ParseException {Token t;
        int n;
        ArrayList<Integer> st = new ArrayList< >();
        ArrayList<String> op = new ArrayList< >();
    t = jj_consume_token(number);
n=Integer.parseInt(t.image); st.add(n);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:{
        sum(st,op);
        break;
        }
      case subtract:{
        sub(st,op);
        break;
        }
      case multiply:{
        mul(st,op);
        break;
        }
      case division:{
        div(st,op);
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:
      case subtract:
      case multiply:
      case division:{
        ;
        break;
        }
      default:
        jj_la1[8] = jj_gen;
        break label_2;
      }
    }
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case equal:{
        ;
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        break label_3;
      }
      jj_consume_token(equal);
Iterator<String> it = op.iterator();
  System.out.println(st);
  System.out.println(op);
  while(!op.isEmpty()) {
    while(it.hasNext()) {
      String i =it.next();
      if(i=="*" || i=="/") {
                int index = op.indexOf(i);
                System.out.println("index="+index);
                it.remove();
                int x;
                if(i=="*")
            x=st.get(index)*st.get(index+1);
            else
         x=st.get(index)/st.get(index+1);
                st.remove(index+1);st.remove(index);
                System.out.println("x="+x);
                st.add(index,x);
                System.out.println(st);
                System.out.println(op);
  }}
it = op.iterator();
        while(it.hasNext()) {
      String i =it.next();
      if(i=="+" || i=="-") {
                int index = op.indexOf(i);
                System.out.println("index="+index);
                it.remove();
                int x;
                if(i=="+")
            x=st.get(index)+st.get(index+1);
            else
         x=st.get(index)-st.get(index+1);
                st.remove(index+1);st.remove(index);
                System.out.println("x="+x);
                st.add(index,x);
                System.out.println(st);
  System.out.println(op);
  }}}
  System.out.println("The Last Result is: "+st.get(0));
    }
}

  static final public void sum(ArrayList<Integer> st,ArrayList<String> op) throws ParseException {Token t;
  int n;
    label_4:
    while (true) {
      jj_consume_token(PLUS);
      t = jj_consume_token(number);
n=Integer.parseInt(t.image); st.add(n); op.add("+");
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:{
        ;
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        break label_4;
      }
    }
}

  static final public void sub(ArrayList<Integer> st,ArrayList<String> op) throws ParseException {Token t;
  int n;
    label_5:
    while (true) {
      jj_consume_token(subtract);
      t = jj_consume_token(number);
n=Integer.parseInt(t.image); st.add(n); op.add("-");
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case subtract:{
        ;
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        break label_5;
      }
    }
}

  static final public void mul(ArrayList<Integer> st,ArrayList<String> op) throws ParseException {Token t;
  int n;
    label_6:
    while (true) {
      jj_consume_token(multiply);
      t = jj_consume_token(number);
n=Integer.parseInt(t.image); st.add(n); op.add("*");
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case multiply:{
        ;
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        break label_6;
      }
    }
}

  static final public void div(ArrayList<Integer> st,ArrayList<String> op) throws ParseException {Token t;
  int n;
    label_7:
    while (true) {
      jj_consume_token(division);
      t = jj_consume_token(number);
n=Integer.parseInt(t.image); st.add(n); op.add("/");
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case division:{
        ;
        break;
        }
      default:
        jj_la1[13] = jj_gen;
        break label_7;
      }
    }
}

//mathematical operation
  static final public void oparith() throws ParseException {
    label_8:
    while (true) {
      operator();
      terms();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:
      case subtract:
      case multiply:
      case division:
      case rest:{
        ;
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        break label_8;
      }
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case equal:{
      jj_consume_token(equal);
      terms();
      break;
      }
    default:
      jj_la1[15] = jj_gen;
      ;
    }
}

//logical operation
  static final public void oplogic() throws ParseException {
    label_9:
    while (true) {
      logic();
      values();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case big:
      case bigeq:
      case small:
      case smalleq:
      case equaltoo:
      case notequal:
      case not:
      case and:
      case or:{
        ;
        break;
        }
      default:
        jj_la1[16] = jj_gen;
        break label_9;
      }
    }
}

//Choose a operators
  static final public void operator() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PLUS:{
      jj_consume_token(PLUS);
      break;
      }
    case subtract:{
      jj_consume_token(subtract);
      break;
      }
    case multiply:{
      jj_consume_token(multiply);
      break;
      }
    case division:{
      jj_consume_token(division);
      break;
      }
    case rest:{
      jj_consume_token(rest);
      break;
      }
    default:
      jj_la1[17] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

//Choose a logic
  static final public void logic() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case big:{
      jj_consume_token(big);
      break;
      }
    case bigeq:{
      jj_consume_token(bigeq);
      break;
      }
    case small:{
      jj_consume_token(small);
      break;
      }
    case smalleq:{
      jj_consume_token(smalleq);
      break;
      }
    case equaltoo:{
      jj_consume_token(equaltoo);
      break;
      }
    case notequal:{
      jj_consume_token(notequal);
      break;
      }
    case not:{
      jj_consume_token(not);
      break;
      }
    case and:{
      jj_consume_token(and);
      break;
      }
    case or:{
      jj_consume_token(or);
      break;
      }
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void arith() throws ParseException {
    label_10:
    while (true) {
      operator();
      jj_consume_token(number);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:
      case subtract:
      case multiply:
      case division:
      case rest:{
        ;
        break;
        }
      default:
        jj_la1[19] = jj_gen;
        break label_10;
      }
    }
}

//Choose a statments for instructions
  static final public void statments() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INIT:
    case FLOAT:
    case DOUBLE:
    case CHR:
    case STR:
    case BOL:{
      declear();
      break;
      }
    case Input:
    case Output:{
      print();
      break;
      }
    case number:{
      select();
      break;
      }
    default:
      jj_la1[20] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(semi);
}

//print a statments for instructions
  static final public void print() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Input:{
      jj_consume_token(Input);
      jj_consume_token(small);
      jj_consume_token(small);
      jj_consume_token(STRING);
      break;
      }
    case Output:{
      jj_consume_token(Output);
      jj_consume_token(big);
      jj_consume_token(big);
      values();
      break;
      }
    default:
      jj_la1[21] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

//Definition loop
  static final public void loop() throws ParseException {
    jj_consume_token(WHILE);
    jj_consume_token(po);
    select();
    jj_consume_token(pc);
    jj_consume_token(bo);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INIT:
    case FLOAT:
    case DOUBLE:
    case CHR:
    case STR:
    case BOL:
    case Input:
    case Output:
    case number:{
      label_11:
      while (true) {
        statments();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case INIT:
        case FLOAT:
        case DOUBLE:
        case CHR:
        case STR:
        case BOL:
        case Input:
        case Output:
        case number:{
          ;
          break;
          }
        default:
          jj_la1[22] = jj_gen;
          break label_11;
        }
      }
      break;
      }
    default:
      jj_la1[23] = jj_gen;
      ;
    }
    jj_consume_token(bc);
}

//Definition condition 
  static final public void condition() throws ParseException {
    jj_consume_token(IF);
    jj_consume_token(po);
    select();
    jj_consume_token(pc);
    jj_consume_token(bo);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INIT:
    case FLOAT:
    case DOUBLE:
    case CHR:
    case STR:
    case BOL:
    case Input:
    case Output:
    case number:{
      label_12:
      while (true) {
        statments();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case INIT:
        case FLOAT:
        case DOUBLE:
        case CHR:
        case STR:
        case BOL:
        case Input:
        case Output:
        case number:{
          ;
          break;
          }
        default:
          jj_la1[24] = jj_gen;
          break label_12;
        }
      }
      break;
      }
    default:
      jj_la1[25] = jj_gen;
      ;
    }
    jj_consume_token(bc);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ELSEIF:{
      label_13:
      while (true) {
        jj_consume_token(ELSEIF);
        jj_consume_token(po);
        select();
        jj_consume_token(pc);
        jj_consume_token(bo);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case INIT:
        case FLOAT:
        case DOUBLE:
        case CHR:
        case STR:
        case BOL:
        case Input:
        case Output:
        case number:{
          label_14:
          while (true) {
            statments();
            switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
            case INIT:
            case FLOAT:
            case DOUBLE:
            case CHR:
            case STR:
            case BOL:
            case Input:
            case Output:
            case number:{
              ;
              break;
              }
            default:
              jj_la1[26] = jj_gen;
              break label_14;
            }
          }
          break;
          }
        default:
          jj_la1[27] = jj_gen;
          ;
        }
        jj_consume_token(bc);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ELSEIF:{
          ;
          break;
          }
        default:
          jj_la1[28] = jj_gen;
          break label_13;
        }
      }
      break;
      }
    default:
      jj_la1[29] = jj_gen;
      ;
    }
    jj_consume_token(ELSE);
    jj_consume_token(bo);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INIT:
    case FLOAT:
    case DOUBLE:
    case CHR:
    case STR:
    case BOL:
    case Input:
    case Output:
    case number:{
      label_15:
      while (true) {
        statments();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case INIT:
        case FLOAT:
        case DOUBLE:
        case CHR:
        case STR:
        case BOL:
        case Input:
        case Output:
        case number:{
          ;
          break;
          }
        default:
          jj_la1[30] = jj_gen;
          break label_15;
        }
      }
      break;
      }
    default:
      jj_la1[31] = jj_gen;
      ;
    }
    jj_consume_token(bc);
}

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public testTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[32];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x0,0x3e00,0x3e00,0x4000000,0x0,0x40000,0x0,0x1e00,0x1e00,0x40000,0x200,0x400,0x800,0x1000,0x3e00,0x40000,0xfbc000,0x3e00,0xfbc000,0x3e00,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x10,0x10,0x0,0x0,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0xa000,0x0,0x0,0xa400,0xfc,0x0,0x2000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x23fc,0x300,0x23fc,0x23fc,0x23fc,0x23fc,0x23fc,0x23fc,0x0,0x0,0x23fc,0x23fc,};
	}

  /** Constructor with InputStream. */
  public test(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public test(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new testTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 32; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 32; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public test(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new testTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 32; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new testTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 32; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public test(testTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 32; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(testTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 32; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[52];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 32; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 52; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
