female(ana).
female(sue).
female(kat).
female(fey).
female(may).
female(pam).
female(liz).
female(syd).
male(tio).
male(kam).
male(rob).
male(dom).
male(dag).
male(jeb).
male(zev).
male(gio).
mother_of(ana,rob).
mother_of(ana,syd).
mother_of(sue,kat).
mother_of(sue,dom).
mother_of(may,tio).
mother_of(may,pam).
mother_of(syd,dag).
mother_of(pam,gio).
mother_of(pam,liz).
mother_of(syd,fey).
father_of(kam,rob).
father_of(kam,syd).
father_of(rob,kat).
father_of(rob,dom).
father_of(jeb,tio).
father_of(jeb,pam).
father_of(tio,fey).
father_of(tio,dag).
father_of(zev,gio).
father_of(zev,liz).
parent_of(X,Y):-mother_of(X,Y);father_of(X,Y).
sblings(X,Y):-father_of(Z,X),father_of(Z,Y),mother_of(M,X),mother_of(M,Y),Y\=X.
grandmother_of(X,Y):-mother_of(X,Z),mother_of(Z,Y).
grandmother_of(X,Y):-mother_of(X,Z),father_of(Z,Y).
grandfather_of(X,Y):-father_of(X,Z),mother_of(Z,Y);mother_of(X,Z),father_of(Z,Y).
uncle_of(X,Y):-male(X),sblings(X,Z),father_of(Z,Y).
aunt_of(X,Y):-female(X),sblings(X,Z),mother_of(Z,Y).
cousins(X,Y):-father_of(Z,X),father_of(E,Y),sblings(Z,E),male(Z),male(E).
cousins(X,Y):-mother_of(Z,X),mother_of(E,Y),sblings(Z,E),female(Z),female(E).
cousins(X,Y):-mother_of(Z,X),father_of(E,Y),sblings(Z,E),female(Z),male(E).
cousins(X,Y):-father_of(Z,X),mother_of(E,Y),sblings(Z,E),male(Z),female(E).



